specfile_path: package/fedora/freecad.spec
additional_packages:
  - python3
actions:
  changelog-entry:
    - bash -c 'git log --no-merges --pretty="format:- %s (%an)" $(git describe --tags --abbrev=0 )..HEAD -- |sed 's/%/%%/g''
  create-archive:
    - git submodule update --init
    - bash -c 'git ls-files --recurse-submodules | tar  -caf freecad-sources.tar.gz -T-'
    - echo -n 'freecad-sources.tar.gz'
downstream_package_name: freecad
jobs:
- job: copr_build
  identifier: pull_request
  trigger: pull_request
  #replace branch with main before merging
  branch: packit
  targets:
  - fedora-41
  - fedora-42

- job: copr_build
  identifier: main
  trigger: commit
  #replace branch with main before merging
  branch: packit
  #replace owner with @freecad and the desired project before merging
  owner: filippor
  project: packit

- job: copr_build
  identifier: release
  trigger: release
  #replace owner with @freecad and the desired project before merging
  owner: filippor
  project: release








