specfile_path: freecad.spec
actions:
  post-upstream-clone:
    - rm -rf packit
    - python package/fedora/make_version_file.py freecad_version.txt
    - bash package/fedora/generate_spec_from_version.sh 1.1.0~pre
  changelog-entry:
    - bash -c 'git log --no-merges --pretty="format:- %s (%an)" -n5'
  create-archive:
    - git submodule update --init
    - mkdir -p .packit
    # Create an archive file with the ‹pkg› directory prefix
    - bash -c 'git ls-files --recurse-submodules | tar  -caf freecad-sources.tar.gz -T-'
    - echo -n 'freecad-sources.tar.gz'

upstream_package_name: freecad
downstream_package_name: freecad
jobs:
- job: copr_build
  trigger: pull_request
  targets:
    - fedora-41
    - fedora-42






