specfile_path: packit/freecad.spec
actions:
  post-upstream-clone: package/fedora/prepare_packit_spec.sh
  changelog-entry:
  - bash -c 'git log --no-merges --pretty="format:- %s (%an)" -n5'
  create-archive:
  - git submodule update --init
  - mkdir -p .packit
  # Create an archive file with the ‹pkg› directory prefix
  - bash -c 'git ls-files --recurse-submodules | tar  -caf packit/freecad.tar.gz -T-'
  - echo -n 'packit/freecad.tar.gz'

upstream_package_name: freecad
downstream_package_name: freecad
jobs:
- job: copr_build
  trigger: pull_request
  targets: [fedora-stable]
- job: tests
  trigger: pull_request
  metadata:
  targets:
    - fedora-41
    - fedora-42





