name: Nightly Rebase from Upstream

on:
  schedule:
    - cron: "0 3 * * *"  # Ogni notte alle 03:00 UTC
  workflow_dispatch:     # Permette anche di lanciarlo manualmente

jobs:
  rebase:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout your repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 100  # Necessario per il rebase

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/FreeCAD/FreeCAD.git
          git fetch --shallow-since="2025-04-01" upstream main

      - name: Rebase your branch onto upstream
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout copr
          git rebase upstream/main

      - name: Push rebased branch
        run: |
          git push origin copr --force-with-lease
