name: Weekly COPR Build

on:
  schedule:
    - cron: '0 8 * * 1'  # Every Monday at 08:00 UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  copr-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger COPR build via webhook
        run: |
          curl -X POST "${{ secrets.COPR_WEBHOOK_URL }}"
